package com.chinamobile.hnu.xiangyu.social.pojo;

import java.util.Date;
import java.util.List;

import com.chinamobile.hnu.xiangyu.user.pojo.UserLabel;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Social {
	public static final byte STATUS_ENABLED = 0;
	public static final byte STATUS_DISABLED = 1;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.user_id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer user_id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	@JsonFormat(pattern = "yyyy-MM-dd", timezone = "GMT+8")
	private Date gmtCreate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtModified;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.telephone
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String telephone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.sex
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte sex;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.nickname
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String nickname;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.college
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String college;

	private Integer grade;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.experience
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer experience;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.password
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String password;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.enable
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte enable;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.cert_flag
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte certFlag;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user_account.header
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String header;
    private Date birthday;
    private String descroption;
    private double longitude;
    private double latitude;



	/**
	 * login_time
	 */
	private Date loginTime;

	private Byte settingClub;

	private Byte settingAsk;

	private Integer roleId;
	
	private Integer totalExperience;
	
	private Integer needExperience;
	
	private String userNickName;
	
	/****
	 * 用户好友备注名，即好友id
	 */
	private Integer uid;
	
	private List<UserLabel> userLabels;








    public Integer getUser_id() {
        return user_id;
    }

    public void setUser_id(Integer user_id) {
        this.user_id = user_id;
    }

    public Date getBirthday() {
        return birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public String getDescroption() {
        return descroption;
    }

    public void setDescroption(String descroption) {
        this.descroption = descroption;
    }

	public double getLongitude() { return longitude; }

	public void setLongitude(double longitude) { this.longitude = longitude; }

	public double getLatitude() { return latitude; }

	public void setLatitude(double latitude) { this.latitude = latitude; }

	public List<UserLabel> getUserLabels() {
		return userLabels;
	}

	public void setUserLabels(List<UserLabel> userLabels) {
		this.userLabels = userLabels;
	}

	public String getUserNickName() {
		return userNickName;
	}

	public void setUserNickName(String userNickName) {
		this.userNickName = userNickName;
	}

	public Integer getUid() {
		return uid;
	}

	public void setUid(Integer uid) {
		this.uid = uid;
	}

	public Integer getNeedExperience() {
		return needExperience;
	}

	public void setNeedExperience(Integer needExperience) {
		this.needExperience = needExperience;
	}

	public Integer getTotalExperience() {
		return totalExperience;
	}

	public void setTotalExperience(Integer totalExperience) {
		this.totalExperience = totalExperience;
	}

	public Integer getRoleId() {
		return roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * @return the settingClub
	 */
	public Byte getSettingClub() {
		return settingClub;
	}

	/**
	 * @param settingClub
	 *            the settingClub to set
	 */
	public void setSettingClub(Byte settingClub) {
		this.settingClub = settingClub;
	}

	/**
	 * @return the settingAsk
	 */
	public Byte getSettingAsk() {
		return settingAsk;
	}

	/**
	 * @param settingAsk
	 *            the settingAsk to set
	 */
	public void setSettingAsk(Byte settingAsk) {
		this.settingAsk = settingAsk;
	}

	/**
	 * @return the grade
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * @param grade
	 *            the grade to set
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.user_id
	 *
	 * @return the value of user_account.user_id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getId() {
		return user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.user_id
	 *
	 * @param user_id
	 *            the value for user_account.user_id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Integer user_id) {
		this.user_id = user_id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.gmt_create
	 *
	 * @return the value of user_account.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for user_account.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.gmt_modified
	 *
	 * @return the value of user_account.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for user_account.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.telephone
	 *
	 * @return the value of user_account.telephone
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getTelephone() {
		return telephone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.telephone
	 *
	 * @param telephone
	 *            the value for user_account.telephone
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setTelephone(String telephone) {
		this.telephone = telephone == null ? null : telephone.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.sex
	 *
	 * @return the value of user_account.sex
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.sex
	 *
	 * @param sex
	 *            the value for user_account.sex
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setSex(Byte sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.nickname
	 *
	 * @return the value of user_account.nickname
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.nickname
	 *
	 * @param nickname
	 *            the value for user_account.nickname
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.college
	 *
	 * @return the value of user_account.college
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getCollege() {
		return college;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.college
	 *
	 * @param college
	 *            the value for user_account.college
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCollege(String college) {
		this.college = college == null ? null : college.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.experience
	 *
	 * @return the value of user_account.experience
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getExperience() {
		return experience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.experience
	 *
	 * @param experience
	 *            the value for user_account.experience
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.password
	 *
	 * @return the value of user_account.password
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.password
	 *
	 * @param password
	 *            the value for user_account.password
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.enable
	 *
	 * @return the value of user_account.enable
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getEnable() {
		return enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.enable
	 *
	 * @param enable
	 *            the value for user_account.enable
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setEnable(Byte enable) {
		this.enable = enable;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.cert_flag
	 *
	 * @return the value of user_account.cert_flag
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getCertFlag() {
		return certFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.cert_flag
	 *
	 * @param certFlag
	 *            the value for user_account.cert_flag
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCertFlag(Byte certFlag) {
		this.certFlag = certFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user_account.header
	 *
	 * @return the value of user_account.header
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getHeader() {
		return header;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user_account.header
	 *
	 * @param header
	 *            the value for user_account.header
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setHeader(String header) {
		this.header = header == null ? null : header.trim();
	}

	public Date getLoginTime() {
		return loginTime;
	}

	public void setLoginTime(Date loginTime) {
		this.loginTime = loginTime;
	}

	@Override
	public String toString() {
		return "UserAccount [id=" + user_id + ", telephone=" + telephone + "]";
	}
}