package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AskComment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.id
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.ask_id
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Long askId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.gmt_create
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+8")
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.gmt_modified
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.presentor
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer presentor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.content
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.like_amount
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer likeAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.comment_amount
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer commentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.status
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column ask_comment.anonymity
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte anonymity;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.id
	 * 
	 * @return the value of ask_comment.id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.id
	 * 
	 * @param id
	 *            the value for ask_comment.id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.ask_id
	 * 
	 * @return the value of ask_comment.ask_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Long getAskId() {
		return askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.ask_id
	 * 
	 * @param askId
	 *            the value for ask_comment.ask_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setAskId(Long askId) {
		this.askId = askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.gmt_create
	 * 
	 * @return the value of ask_comment.gmt_create
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.gmt_create
	 * 
	 * @param gmtCreate
	 *            the value for ask_comment.gmt_create
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.gmt_modified
	 * 
	 * @return the value of ask_comment.gmt_modified
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.gmt_modified
	 * 
	 * @param gmtModified
	 *            the value for ask_comment.gmt_modified
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.presentor
	 * 
	 * @return the value of ask_comment.presentor
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getPresentor() {
		return presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.presentor
	 * 
	 * @param presentor
	 *            the value for ask_comment.presentor
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentor(Integer presentor) {
		this.presentor = presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.content
	 * 
	 * @return the value of ask_comment.content
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.content
	 * 
	 * @param content
	 *            the value for ask_comment.content
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.like_amount
	 * 
	 * @return the value of ask_comment.like_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getLikeAmount() {
		return likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.like_amount
	 * 
	 * @param likeAmount
	 *            the value for ask_comment.like_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setLikeAmount(Integer likeAmount) {
		this.likeAmount = likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.comment_amount
	 * 
	 * @return the value of ask_comment.comment_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getCommentAmount() {
		return commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.comment_amount
	 * 
	 * @param commentAmount
	 *            the value for ask_comment.comment_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCommentAmount(Integer commentAmount) {
		this.commentAmount = commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.status
	 * 
	 * @return the value of ask_comment.status
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.status
	 * 
	 * @param status
	 *            the value for ask_comment.status
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_comment.anonymity
	 * 
	 * @return the value of ask_comment.anonymity
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getAnonymity() {
		return anonymity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_comment.anonymity
	 * 
	 * @param anonymity
	 *            the value for ask_comment.anonymity
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setAnonymity(Byte anonymity) {
		this.anonymity = anonymity;
	}
}