package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

public class AskCommentLike {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column club_speak_like.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer id;
	private Long commentId;
	private Integer memberId;
	private Date gmtCreate;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getCommentId() {
		return commentId;
	}

	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	public Integer getMemberId() {
		return memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	public Date getGmtCreate() {
		return gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

}