package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

public class AskInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.gmt_create
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.gmt_modified
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtModified;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.presentor
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer presentor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.content
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.like_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer likeAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.comment_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer commentAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer visitAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.yesterday_visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer yesterdayVisitAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.anonymity
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Byte anonymity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.special_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Integer specialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_info.status
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.id
	 * @return  the value of ask_info.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.id
	 * @param id  the value for ask_info.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.gmt_create
	 * @return  the value of ask_info.gmt_create
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.gmt_create
	 * @param gmtCreate  the value for ask_info.gmt_create
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.gmt_modified
	 * @return  the value of ask_info.gmt_modified
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.gmt_modified
	 * @param gmtModified  the value for ask_info.gmt_modified
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.name
	 * @return  the value of ask_info.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.name
	 * @param name  the value for ask_info.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.presentor
	 * @return  the value of ask_info.presentor
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getPresentor() {
		return presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.presentor
	 * @param presentor  the value for ask_info.presentor
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentor(Integer presentor) {
		this.presentor = presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.content
	 * @return  the value of ask_info.content
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.content
	 * @param content  the value for ask_info.content
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.like_amount
	 * @return  the value of ask_info.like_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getLikeAmount() {
		return likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.like_amount
	 * @param likeAmount  the value for ask_info.like_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setLikeAmount(Integer likeAmount) {
		this.likeAmount = likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.comment_amount
	 * @return  the value of ask_info.comment_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getCommentAmount() {
		return commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.comment_amount
	 * @param commentAmount  the value for ask_info.comment_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setCommentAmount(Integer commentAmount) {
		this.commentAmount = commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.visit_amount
	 * @return  the value of ask_info.visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getVisitAmount() {
		return visitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.visit_amount
	 * @param visitAmount  the value for ask_info.visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setVisitAmount(Integer visitAmount) {
		this.visitAmount = visitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.yesterday_visit_amount
	 * @return  the value of ask_info.yesterday_visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getYesterdayVisitAmount() {
		return yesterdayVisitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.yesterday_visit_amount
	 * @param yesterdayVisitAmount  the value for ask_info.yesterday_visit_amount
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setYesterdayVisitAmount(Integer yesterdayVisitAmount) {
		this.yesterdayVisitAmount = yesterdayVisitAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.anonymity
	 * @return  the value of ask_info.anonymity
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Byte getAnonymity() {
		return anonymity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.anonymity
	 * @param anonymity  the value for ask_info.anonymity
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setAnonymity(Byte anonymity) {
		this.anonymity = anonymity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.special_id
	 * @return  the value of ask_info.special_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Integer getSpecialId() {
		return specialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.special_id
	 * @param specialId  the value for ask_info.special_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setSpecialId(Integer specialId) {
		this.specialId = specialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_info.status
	 * @return  the value of ask_info.status
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_info.status
	 * @param status  the value for ask_info.status
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}