package com.chinamobile.hnu.xiangyu.ask.pojo;

public class AskLabel {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_label.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_label.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_label.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Long askId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_label.id
	 * @return  the value of ask_label.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_label.id
	 * @param id  the value for ask_label.id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_label.name
	 * @return  the value of ask_label.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_label.name
	 * @param name  the value for ask_label.name
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_label.ask_id
	 * @return  the value of ask_label.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Long getAskId() {
		return askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_label.ask_id
	 * @param askId  the value for ask_label.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setAskId(Long askId) {
		this.askId = askId;
	}
}