package com.chinamobile.hnu.xiangyu.ask.pojo;

public class AskPhoto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_photo.photo_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private String photoId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ask_photo.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	private Long askId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_photo.photo_id
	 * @return  the value of ask_photo.photo_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public String getPhotoId() {
		return photoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_photo.photo_id
	 * @param photoId  the value for ask_photo.photo_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setPhotoId(String photoId) {
		this.photoId = photoId == null ? null : photoId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ask_photo.ask_id
	 * @return  the value of ask_photo.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public Long getAskId() {
		return askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ask_photo.ask_id
	 * @param askId  the value for ask_photo.ask_id
	 * @mbg.generated  Thu May 17 23:34:42 CST 2018
	 */
	public void setAskId(Long askId) {
		this.askId = askId;
	}
}