package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * 
 * 
 * <p>
 * Title: AskSpecial.java
 * </p>
 * 
 * <p>
 * Description: 专场基本信息
 * </p>
 * 
 * @author lh
 * 
 * @date 2018年6月5日
 * 
 * @version 1.0
 */
public class AskSpecial {

	private Integer id;

	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm")
	private Date gmtCreate;

	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm")
	private Date gmtModified;

	private String title;

	private Byte category;

	private Integer presentor;

	private String presentorName;

	private String presentorJob;

	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm")
	private Date beginTime;

	@JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm")
	private Date endTime;

	private String coverImage;

	private Integer likeAmount;

	private Integer commentAmount;

	private Date lastCommentTime;

	private Byte status;

	private Byte recommend;

	private String introduction;

	// 专家id
	private Integer expertId;

	@Transient
	private String time;

	// 1-已赞，null-未赞
	private Integer isLike;

	public Integer getExpertId() {
		return expertId;
	}

	public void setExpertId(Integer expertId) {
		this.expertId = expertId;
	}

	public Integer getIsLike() {
		return isLike;
	}

	public void setIsLike(Integer isLike) {
		this.isLike = isLike;
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.id
	 * 
	 * @param id
	 *            the value for ask_special.id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.gmt_create
	 * 
	 * @return the value of ask_special.gmt_create
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.gmt_create
	 * 
	 * @param gmtCreate
	 *            the value for ask_special.gmt_create
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.gmt_modified
	 * 
	 * @return the value of ask_special.gmt_modified
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.gmt_modified
	 * 
	 * @param gmtModified
	 *            the value for ask_special.gmt_modified
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.title
	 * 
	 * @return the value of ask_special.title
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.title
	 * 
	 * @param title
	 *            the value for ask_special.title
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setTitle(String title) {
		this.title = title == null ? null : title.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.category
	 * 
	 * @return the value of ask_special.category
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.category
	 * 
	 * @param category
	 *            the value for ask_special.category
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCategory(Byte category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.presentor
	 * 
	 * @return the value of ask_special.presentor
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getPresentor() {
		return presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.presentor
	 * 
	 * @param presentor
	 *            the value for ask_special.presentor
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentor(Integer presentor) {
		this.presentor = presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.presentor_name
	 * 
	 * @return the value of ask_special.presentor_name
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getPresentorName() {
		return presentorName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.presentor_name
	 * 
	 * @param presentorName
	 *            the value for ask_special.presentor_name
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentorName(String presentorName) {
		this.presentorName = presentorName == null ? null : presentorName
				.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.presentor_job
	 * 
	 * @return the value of ask_special.presentor_job
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getPresentorJob() {
		return presentorJob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.presentor_job
	 * 
	 * @param presentorJob
	 *            the value for ask_special.presentor_job
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentorJob(String presentorJob) {
		this.presentorJob = presentorJob == null ? null : presentorJob.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.begin_time
	 * 
	 * @return the value of ask_special.begin_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getBeginTime() {
		return beginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.begin_time
	 * 
	 * @param beginTime
	 *            the value for ask_special.begin_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.end_time
	 * 
	 * @return the value of ask_special.end_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.end_time
	 * 
	 * @param endTime
	 *            the value for ask_special.end_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.cover_image
	 * 
	 * @return the value of ask_special.cover_image
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getCoverImage() {
		return coverImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.cover_image
	 * 
	 * @param coverImage
	 *            the value for ask_special.cover_image
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage == null ? null : coverImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.like_amount
	 * 
	 * @return the value of ask_special.like_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getLikeAmount() {
		return likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.like_amount
	 * 
	 * @param likeAmount
	 *            the value for ask_special.like_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setLikeAmount(Integer likeAmount) {
		this.likeAmount = likeAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.comment_amount
	 * 
	 * @return the value of ask_special.comment_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getCommentAmount() {
		return commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.comment_amount
	 * 
	 * @param commentAmount
	 *            the value for ask_special.comment_amount
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCommentAmount(Integer commentAmount) {
		this.commentAmount = commentAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.last_comment_time
	 * 
	 * @return the value of ask_special.last_comment_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getLastCommentTime() {
		return lastCommentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.last_comment_time
	 * 
	 * @param lastCommentTime
	 *            the value for ask_special.last_comment_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setLastCommentTime(Date lastCommentTime) {
		this.lastCommentTime = lastCommentTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.status
	 * 
	 * @return the value of ask_special.status
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.status
	 * 
	 * @param status
	 *            the value for ask_special.status
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.recommend
	 * 
	 * @return the value of ask_special.recommend
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getRecommend() {
		return recommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.recommend
	 * 
	 * @param recommend
	 *            the value for ask_special.recommend
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setRecommend(Byte recommend) {
		this.recommend = recommend;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_special.introduction
	 * 
	 * @return the value of ask_special.introduction
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_special.introduction
	 * 
	 * @param introduction
	 *            the value for ask_special.introduction
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction == null ? null : introduction.trim();
	}
}