package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

public class AskspecialLike {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column club_speak_like.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer id;
	private Integer specialId;
	private Integer memberId;
	private Date gmtCreate;

	public Integer getSpecialId() {
		return specialId;
	}

	public void setSpecialId(Integer specialId) {
		this.specialId = specialId;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMemberId() {
		return memberId;
	}

	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column club_speak_like.gmt_create
	 *
	 * @return the value of club_speak_like.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column club_speak_like.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for club_speak_like.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}
}