package com.chinamobile.hnu.xiangyu.ask.pojo;

import java.util.Date;

/**
 * 
 * 
 * <p>
 * Title: AskVisitHistory.java
 * </p>
 * 
 * <p>
 * Description: 访问历史记录
 * </p>
 * 
 * @author lh
 * 
 * @date 2018年6月5日
 * 
 * @version 1.0
 */
public class AskVisitHistory {

	private Long id;

	private Integer memberId;

	private Long askId;

	private Date visitTime;

	private Integer countNumber;

	public Integer getCountNumber() {
		return countNumber;
	}

	public void setCountNumber(Integer countNumber) {
		this.countNumber = countNumber;
	}

	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_visit_history.id
	 * 
	 * @param id
	 *            the value for ask_visit_history.id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_visit_history.member_id
	 * 
	 * @return the value of ask_visit_history.member_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getMemberId() {
		return memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_visit_history.member_id
	 * 
	 * @param memberId
	 *            the value for ask_visit_history.member_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setMemberId(Integer memberId) {
		this.memberId = memberId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_visit_history.ask_id
	 * 
	 * @return the value of ask_visit_history.ask_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Long getAskId() {
		return askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_visit_history.ask_id
	 * 
	 * @param askId
	 *            the value for ask_visit_history.ask_id
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setAskId(Long askId) {
		this.askId = askId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column ask_visit_history.visit_time
	 * 
	 * @return the value of ask_visit_history.visit_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getVisitTime() {
		return visitTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column ask_visit_history.visit_time
	 * 
	 * @param visitTime
	 *            the value for ask_visit_history.visit_time
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setVisitTime(Date visitTime) {
		this.visitTime = visitTime;
	}
}