package com.chinamobile.hnu.xiangyu.common.pojo;

import java.util.Date;

public class PubAdvertisement {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtCreate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Date gmtModified;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.name
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.cover_image
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String coverImage;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.link_url
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private String linkUrl;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column pub_advertisement.category
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	private Byte category;

	private String content;

	private String description;

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.id
	 *
	 * @return the value of pub_advertisement.id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.id
	 *
	 * @param id
	 *            the value for pub_advertisement.id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.gmt_create
	 *
	 * @return the value of pub_advertisement.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for pub_advertisement.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.gmt_modified
	 *
	 * @return the value of pub_advertisement.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for pub_advertisement.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.name
	 *
	 * @return the value of pub_advertisement.name
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.name
	 *
	 * @param name
	 *            the value for pub_advertisement.name
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.cover_image
	 *
	 * @return the value of pub_advertisement.cover_image
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getCoverImage() {
		return coverImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.cover_image
	 *
	 * @param coverImage
	 *            the value for pub_advertisement.cover_image
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCoverImage(String coverImage) {
		this.coverImage = coverImage == null ? null : coverImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.link_url
	 *
	 * @return the value of pub_advertisement.link_url
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getLinkUrl() {
		return linkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.link_url
	 *
	 * @param linkUrl
	 *            the value for pub_advertisement.link_url
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setLinkUrl(String linkUrl) {
		this.linkUrl = linkUrl == null ? null : linkUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_advertisement.category
	 *
	 * @return the value of pub_advertisement.category
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_advertisement.category
	 *
	 * @param category
	 *            the value for pub_advertisement.category
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCategory(Byte category) {
		this.category = category;
	}
}