package com.chinamobile.hnu.xiangyu.common.pojo;

import java.util.Date;

public class PubBinding {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_binding.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_binding.phone
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_binding.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_binding.code
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_binding.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_binding.id
     *
     * @return the value of pub_binding.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_binding.id
     *
     * @param id the value for pub_binding.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_binding.phone
     *
     * @return the value of pub_binding.phone
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_binding.phone
     *
     * @param phone the value for pub_binding.phone
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_binding.member_id
     *
     * @return the value of pub_binding.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_binding.member_id
     *
     * @param memberId the value for pub_binding.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_binding.code
     *
     * @return the value of pub_binding.code
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_binding.code
     *
     * @param code the value for pub_binding.code
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_binding.gmt_create
     *
     * @return the value of pub_binding.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_binding.gmt_create
     *
     * @param gmtCreate the value for pub_binding.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}