package com.chinamobile.hnu.xiangyu.common.pojo;

public class PubConstPlane {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_const_plane.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_const_plane.category
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pub_const_plane.value
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_const_plane.id
     *
     * @return the value of pub_const_plane.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_const_plane.id
     *
     * @param id the value for pub_const_plane.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_const_plane.category
     *
     * @return the value of pub_const_plane.category
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_const_plane.category
     *
     * @param category the value for pub_const_plane.category
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCategory(String category) {
        this.category = category == null ? null : category.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pub_const_plane.value
     *
     * @return the value of pub_const_plane.value
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pub_const_plane.value
     *
     * @param value the value for pub_const_plane.value
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}