package com.chinamobile.hnu.xiangyu.common.pojo;

import java.util.Date;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonFormat;

public class PubFeedback {
	private Integer id;

	private Integer presentor;

	@NotBlank(message = "反馈类型不能为空")
	private String category;

	@NotBlank(message = "反馈内容不能为空")
	@Length(max = 512, message = "反馈内容字符过长")
	private String content;

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+8")
	private Date gmtCreate;

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm", timezone = "GMT+8")
	private Date gmtModified;

	private Byte status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.id
	 *
	 * @return the value of pub_feedback.id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.id
	 *
	 * @param id
	 *            the value for pub_feedback.id
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.presentor
	 *
	 * @return the value of pub_feedback.presentor
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Integer getPresentor() {
		return presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.presentor
	 *
	 * @param presentor
	 *            the value for pub_feedback.presentor
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setPresentor(Integer presentor) {
		this.presentor = presentor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.category
	 *
	 * @return the value of pub_feedback.category
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.category
	 *
	 * @param category
	 *            the value for pub_feedback.category
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setCategory(String category) {
		this.category = category == null ? null : category.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.content
	 *
	 * @return the value of pub_feedback.content
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.content
	 *
	 * @param content
	 *            the value for pub_feedback.content
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.gmt_create
	 *
	 * @return the value of pub_feedback.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.gmt_create
	 *
	 * @param gmtCreate
	 *            the value for pub_feedback.gmt_create
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.gmt_modified
	 *
	 * @return the value of pub_feedback.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Date getGmtModified() {
		return gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.gmt_modified
	 *
	 * @param gmtModified
	 *            the value for pub_feedback.gmt_modified
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setGmtModified(Date gmtModified) {
		this.gmtModified = gmtModified;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column pub_feedback.status
	 *
	 * @return the value of pub_feedback.status
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column pub_feedback.status
	 *
	 * @param status
	 *            the value for pub_feedback.status
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}
}