package com.chinamobile.hnu.xiangyu.user.pojo;

import java.util.Date;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

public class UserCertification {
	
    private Integer userId;

    @NotBlank(message="证件号码不能为空")
    @Length(max=18,message="证件号码字符过长")
    private String idcardNumber;

    private String idcardPositive;

    private String idcardNegative;

    @NotBlank(message="姓名不能为空")
    @Length(max=16,message="姓名字符过长")
    private String name;

    private Date idcardValidityFrom;

    private Date idcardValidityTo;

    private Byte status;
    
    private String cardType;
    

    /**
	 * @return the cardType
	 */
	public String getCardType() {
		return cardType;
	}

	/**
	 * @param cardType the cardType to set
	 */
	public void setCardType(String cardType) {
		this.cardType = cardType;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_certification.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_certification.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.user_id
     *
     * @return the value of user_certification.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.user_id
     *
     * @param userId the value for user_certification.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.idcard_number
     *
     * @return the value of user_certification.idcard_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getIdcardNumber() {
        return idcardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.idcard_number
     *
     * @param idcardNumber the value for user_certification.idcard_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIdcardNumber(String idcardNumber) {
        this.idcardNumber = idcardNumber == null ? null : idcardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.idcard_positive
     *
     * @return the value of user_certification.idcard_positive
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getIdcardPositive() {
        return idcardPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.idcard_positive
     *
     * @param idcardPositive the value for user_certification.idcard_positive
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIdcardPositive(String idcardPositive) {
        this.idcardPositive = idcardPositive == null ? null : idcardPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.idcard_negative
     *
     * @return the value of user_certification.idcard_negative
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getIdcardNegative() {
        return idcardNegative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.idcard_negative
     *
     * @param idcardNegative the value for user_certification.idcard_negative
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIdcardNegative(String idcardNegative) {
        this.idcardNegative = idcardNegative == null ? null : idcardNegative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.name
     *
     * @return the value of user_certification.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.name
     *
     * @param name the value for user_certification.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.idcard_validity_from
     *
     * @return the value of user_certification.idcard_validity_from
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getIdcardValidityFrom() {
        return idcardValidityFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.idcard_validity_from
     *
     * @param idcardValidityFrom the value for user_certification.idcard_validity_from
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIdcardValidityFrom(Date idcardValidityFrom) {
        this.idcardValidityFrom = idcardValidityFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.idcard_validity_to
     *
     * @return the value of user_certification.idcard_validity_to
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getIdcardValidityTo() {
        return idcardValidityTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.idcard_validity_to
     *
     * @param idcardValidityTo the value for user_certification.idcard_validity_to
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIdcardValidityTo(Date idcardValidityTo) {
        this.idcardValidityTo = idcardValidityTo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.status
     *
     * @return the value of user_certification.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.status
     *
     * @param status the value for user_certification.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.gmt_create
     *
     * @return the value of user_certification.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.gmt_create
     *
     * @param gmtCreate the value for user_certification.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_certification.gmt_modified
     *
     * @return the value of user_certification.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_certification.gmt_modified
     *
     * @param gmtModified the value for user_certification.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}