package com.chinamobile.hnu.xiangyu.user.pojo;

public class UserFriendKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_friend.friend_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer friendId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.user_id
     *
     * @return the value of user_friend.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.user_id
     *
     * @param userId the value for user_friend.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_friend.friend_id
     *
     * @return the value of user_friend.friend_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getFriendId() {
        return friendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_friend.friend_id
     *
     * @param friendId the value for user_friend.friend_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setFriendId(Integer friendId) {
        this.friendId = friendId;
    }
}