package com.chinamobile.hnu.xiangyu.user.pojo;

public class UserLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String label;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_label.frequency
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer frequency;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.id
     *
     * @return the value of user_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_label.id
     *
     * @param id the value for user_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.user_id
     *
     * @return the value of user_label.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_label.user_id
     *
     * @param userId the value for user_label.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.label
     *
     * @return the value of user_label.label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getLabel() {
        return label;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_label.label
     *
     * @param label the value for user_label.label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setLabel(String label) {
        this.label = label == null ? null : label.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_label.frequency
     *
     * @return the value of user_label.frequency
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_label.frequency
     *
     * @param frequency the value for user_label.frequency
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setFrequency(Integer frequency) {
        this.frequency = frequency;
    }
}