package com.chinamobile.hnu.xiangyu.user.pojo;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class UserReservedQuestion {
    private Integer id;

    private Integer userId;

    private String content;

    private String answer;

    private Date gmtCreate;

    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.id
     *
     * @return the value of user_reserved_question.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.id
     *
     * @param id the value for user_reserved_question.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.user_id
     *
     * @return the value of user_reserved_question.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.user_id
     *
     * @param userId the value for user_reserved_question.user_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.content
     *
     * @return the value of user_reserved_question.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.content
     *
     * @param content the value for user_reserved_question.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.answer
     *
     * @return the value of user_reserved_question.answer
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.answer
     *
     * @param answer the value for user_reserved_question.answer
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.gmt_create
     *
     * @return the value of user_reserved_question.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.gmt_create
     *
     * @param gmtCreate the value for user_reserved_question.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_reserved_question.gmt_modified
     *
     * @return the value of user_reserved_question.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_reserved_question.gmt_modified
     *
     * @param gmtModified the value for user_reserved_question.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "UserReservedQuestion [id=" + id + ", userId=" + userId + ", content=" + content + ", answer=" + answer
				+ ", gmtCreate=" + gmtCreate + ", gmtModified=" + gmtModified + "]";
	}
    
}