package com.chinamobile.hnu.xiangyu.common.dao;

import java.util.List;

import com.chinamobile.hnu.xiangyu.common.pojo.PubAdvertisement;

public interface PubAdvertisementMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(PubAdvertisement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(PubAdvertisement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	PubAdvertisement selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(PubAdvertisement record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(PubAdvertisement record);

	/**
	 * 查广告图片
	 * 
	 * @param category
	 * @return
	 */
	List<PubAdvertisement> selectByCategory(Integer category);

	/**
	 * 查询所有图片
	 * 
	 * @return
	 */
	List<PubAdvertisement> selectAdvAll();
}