package com.chinamobile.hnu.xiangyu.common.dao;

import java.util.Map;

import com.chinamobile.hnu.xiangyu.common.pojo.PubBinding;

public interface PubBindingMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(PubBinding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(PubBinding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	PubBinding selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(PubBinding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table pub_binding
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(PubBinding record);

	/**
	 * 依据user id，phone，code选择
	 * 
	 * @param bind
	 * @return
	 */
	PubBinding selectByCnd(PubBinding bind);

	/**
	 * 可依据user id，起始时间查询记录个数
	 * 
	 * @param bind
	 * @return
	 */
	Integer countByCnd(PubBinding bind);

	/**
	 * 查询今天插入手机号总条数
	 * 
	 * @param phone
	 *            手机号码
	 * @return
	 */
	Integer getBindCountByNow(String phone);

	/**
	 * 时间间隔以内指定手机号码是否还可以发送验证码
	 * 
	 * @param phone
	 *            手机号码
	 * @param offset
	 *            时间间隔，单位为分钟
	 * @return
	 */
	Integer getBindByTimeOffset(Map<String, Object> param);

	/**
	 * 查询用户输入的注册验证码是否正确
	 * 
	 * @param bindingItem
	 * @return
	 */
	Integer selectBindingCode(PubBinding bindingItem);
}