package com.chinamobile.hnu.xiangyu.common.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.common.pojo.PubConstPlane;

public interface PubConstPlaneMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	PubConstPlane selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(PubConstPlane record);

	/**
	 * select PubConstPlane list By category
	 * 
	 * @param type
	 * @return
	 */
	List<PubConstPlane> selectPlanesByType(String type);

	/**
	 * @param type
	 * @param name
	 * @return
	 */
	List<PubConstPlane> selectPlanesByList(@Param("type") String type,
			@Param("name") String name);

	/**
	 * 批量删除禁用项
	 * 
	 * @param idList
	 * @return
	 */
	int deleteBatchDisableById(List<Integer> idList);

}