package com.chinamobile.hnu.xiangyu.common.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.common.pojo.PubFeedback;
import com.chinamobile.hnu.xiangyu.web.api.vo.FeebackVo;

public interface PubFeedbackMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(PubFeedback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(PubFeedback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	PubFeedback selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(PubFeedback record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_feedback
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(PubFeedback record);

	/**
	 * 反馈列表
	 * 
	 * @param map
	 * @return
	 */
	List<FeebackVo> selectListPageFeeback(Map<String, Object> map);
}