package com.chinamobile.hnu.xiangyu.common.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.common.pojo.SysUserNews;
import com.chinamobile.hnu.xiangyu.web.api.vo.NewsVo;

/**
 * 
 * @author lh <自动生成>
 * @联系QQ：2465613689
 * @version 2018-06-27 10:58:49
 */
public interface SysUserNewsMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(SysUserNews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement fasdfsa
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	SysUserNews selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_advertisement
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(SysUserNews record);

	/**
	 * 更新同意or不同意入群
	 * 
	 * @param record
	 * @return
	 */
	int updateById(SysUserNews record);

	/**
	 * 消息列表
	 * 
	 * @param map
	 * @return
	 */
	List<NewsVo> selectListPageNews(Map<String, Object> map);

	/**
	 * 更新已读
	 * 
	 * @param record
	 * @return
	 */
	int updateByIds(SysUserNews record);

	/**
	 * 清理所有消息
	 * 
	 * @param map
	 */
	int updateNewsById(Map<String, Object> map);

	/**
	 * 查询是否再团
	 * 
	 * @param map
	 * @return
	 */
	SysUserNews selectUserByBizId(Map<String, Object> map);

	/**
	 * 更新加好友状态
	 * 
	 * @param map
	 */
	void updateUserStatus(Map<String, Object> map);
}
