package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClubNotice {
	
	public interface Add{}
	public interface Update{}
	
	@NotNull(message="公共id不能为空",groups={Update.class})
    private Long id;

    private Date gmtCreate;

    private Date gmtModified;

    private Integer presentor;

    @NotNull(message="团队id不能为空",groups={Add.class,Update.class})
    private Integer clubId;
    
    @NotBlank(message="公告标题不能为空",groups={Add.class,Update.class})
    @Length(max=32,message="公告标题字符过长",groups={Add.class,Update.class})
    private String title;

    @NotBlank(message="公告内容不能为空",groups={Add.class,Update.class})
    @Length(max=512,message="公告内容字符过长",groups={Add.class,Update.class})
    private String content;

    private Byte status;

    
    
    /**
	 * @return the clubId
	 */
	public Integer getClubId() {
		return clubId;
	}

	/**
	 * @param clubId the clubId to set
	 */
	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.id
     *
     * @return the value of club_notice.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.id
     *
     * @param id the value for club_notice.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.gmt_create
     *
     * @return the value of club_notice.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.gmt_create
     *
     * @param gmtCreate the value for club_notice.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.gmt_modified
     *
     * @return the value of club_notice.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.gmt_modified
     *
     * @param gmtModified the value for club_notice.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.presentor
     *
     * @return the value of club_notice.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getPresentor() {
        return presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.presentor
     *
     * @param presentor the value for club_notice.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPresentor(Integer presentor) {
        this.presentor = presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.title
     *
     * @return the value of club_notice.title
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.title
     *
     * @param title the value for club_notice.title
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.content
     *
     * @return the value of club_notice.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.content
     *
     * @param content the value for club_notice.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_notice.status
     *
     * @return the value of club_notice.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_notice.status
     *
     * @param status the value for club_notice.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}