package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;

public class ClubVisitHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_visit_history.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_visit_history.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_visit_history.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer clubId;
    
    
    private Integer countNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_visit_history.visit_time
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Date visitTime;
    
    
    

    /**
	 * @return the countNumber
	 */
	public Integer getCountNumber() {
		return countNumber;
	}

	/**
	 * @param countNumber the countNumber to set
	 */
	public void setCountNumber(Integer countNumber) {
		this.countNumber = countNumber;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_visit_history.id
     *
     * @return the value of club_visit_history.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_visit_history.id
     *
     * @param id the value for club_visit_history.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_visit_history.member_id
     *
     * @return the value of club_visit_history.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_visit_history.member_id
     *
     * @param memberId the value for club_visit_history.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

   

    /**
	 * @return the clubId
	 */
	public Integer getClubId() {
		return clubId;
	}

	/**
	 * @param clubId the clubId to set
	 */
	public void setClubId(Integer clubId) {
		this.clubId = clubId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_visit_history.visit_time
     *
     * @return the value of club_visit_history.visit_time
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getVisitTime() {
        return visitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_visit_history.visit_time
     *
     * @param visitTime the value for club_visit_history.visit_time
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setVisitTime(Date visitTime) {
        this.visitTime = visitTime;
    }
}