package com.chinamobile.hnu.xiangyu.club.pojo;

public class ClubSpeakPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_speak_photo.photo_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_speak_photo.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long speakId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak_photo.photo_id
     *
     * @return the value of club_speak_photo.photo_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak_photo.photo_id
     *
     * @param photoId the value for club_speak_photo.photo_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPhotoId(String photoId) {
        this.photoId = photoId == null ? null : photoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak_photo.speak_id
     *
     * @return the value of club_speak_photo.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getSpeakId() {
        return speakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak_photo.speak_id
     *
     * @param speakId the value for club_speak_photo.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSpeakId(Long speakId) {
        this.speakId = speakId;
    }
}