package com.chinamobile.hnu.xiangyu.club.pojo;

public class ClubMemberKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_member.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer clubId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.member_id
     *
     * @return the value of club_member.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.member_id
     *
     * @param memberId the value for club_member.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.club_id
     *
     * @return the value of club_member.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.club_id
     *
     * @param clubId the value for club_member.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }
}