package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClubMember extends ClubMemberKey {
	
	public interface Nick{}
	
    private Date joinTime;

    //团队成员昵称
    @NotBlank(message="昵称不能为空",groups={Nick.class})
    @Length(max=16,message="昵称字符过长",groups={Nick.class})
    private String nickname;

    //成员本身昵称
    private String userName;
    
    private Byte role;
    
    private String header;
    
    @NotNull(message="id不能为空",groups={Nick.class})
    private Long id;
    
    private Integer grade;
    
    private Integer experience;

    

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * @return the grade
	 */
	public Integer getGrade() {
		return grade;
	}

	/**
	 * @param grade the grade to set
	 */
	public void setGrade(Integer grade) {
		this.grade = grade;
	}

	/**
	 * @return the experience
	 */
	public Integer getExperience() {
		return experience;
	}

	/**
	 * @param experience the experience to set
	 */
	public void setExperience(Integer experience) {
		this.experience = experience;
	}

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the header
	 */
	public String getHeader() {
		return header;
	}

	/**
	 * @param header the header to set
	 */
	public void setHeader(String header) {
		this.header = header;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.join_time
     *
     * @return the value of club_member.join_time
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getJoinTime() {
        return joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.join_time
     *
     * @param joinTime the value for club_member.join_time
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setJoinTime(Date joinTime) {
        this.joinTime = joinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.nickname
     *
     * @return the value of club_member.nickname
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.nickname
     *
     * @param nickname the value for club_member.nickname
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_member.role
     *
     * @return the value of club_member.role
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_member.role
     *
     * @param role the value for club_member.role
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setRole(Byte role) {
        this.role = role;
    }
    
    
}