package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

public class ClubTeamBuilding {
	
	public interface Add{}
	public interface Update{}
    
	@NotNull(message="团建id不能为空",groups={Update.class})
    private Long id;
   
    @NotNull(message="团队id不能为空",groups={Add.class})
    private Integer clubId;

    private Date gmtCreate;

    private Date gmtModified;

    private Integer presentor;

    @NotBlank(message="团建标题不能为空",groups={Add.class,Update.class})
    @Length(max=64,message="团建标题字符过长",groups={Add.class,Update.class})
    private String title;

    @NotBlank(message="发布内容不能为空",groups={Add.class,Update.class})
    @Length(max=512,message="发布内容字符过长",groups={Add.class,Update.class})
    private String content;

    private Byte recommend;

    private Integer likeAmount;

    private Integer commentAmount;

    private Byte status;
    
    private List<Photo> photos;
    
    
    /**
	 * @return the photos
	 */
	public List<Photo> getPhotos() {
		return photos;
	}

	/**
	 * @param photos the photos to set
	 */
	public void setPhotos(List<Photo> photos) {
		this.photos = photos;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.id
     *
     * @return the value of club_team_building.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.id
     *
     * @param id the value for club_team_building.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.club_id
     *
     * @return the value of club_team_building.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.club_id
     *
     * @param clubId the value for club_team_building.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.gmt_create
     *
     * @return the value of club_team_building.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.gmt_create
     *
     * @param gmtCreate the value for club_team_building.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.gmt_modified
     *
     * @return the value of club_team_building.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.gmt_modified
     *
     * @param gmtModified the value for club_team_building.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.presentor
     *
     * @return the value of club_team_building.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getPresentor() {
        return presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.presentor
     *
     * @param presentor the value for club_team_building.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPresentor(Integer presentor) {
        this.presentor = presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.title
     *
     * @return the value of club_team_building.title
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.title
     *
     * @param title the value for club_team_building.title
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.content
     *
     * @return the value of club_team_building.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.content
     *
     * @param content the value for club_team_building.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.recommend
     *
     * @return the value of club_team_building.recommend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getRecommend() {
        return recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.recommend
     *
     * @param recommend the value for club_team_building.recommend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setRecommend(Byte recommend) {
        this.recommend = recommend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.like_amount
     *
     * @return the value of club_team_building.like_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getLikeAmount() {
        return likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.like_amount
     *
     * @param likeAmount the value for club_team_building.like_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setLikeAmount(Integer likeAmount) {
        this.likeAmount = likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.comment_amount
     *
     * @return the value of club_team_building.comment_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getCommentAmount() {
        return commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.comment_amount
     *
     * @param commentAmount the value for club_team_building.comment_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCommentAmount(Integer commentAmount) {
        this.commentAmount = commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building.status
     *
     * @return the value of club_team_building.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building.status
     *
     * @param status the value for club_team_building.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}