package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

import com.chinamobile.hnu.xiangyu.user.pojo.UserAccount;


public class ClubInfo {
	
	public interface Add{
		
	}
	
	public interface UpdateBase{
		
	}
	
	public interface Update{
		
	}
	
	@NotNull(message="团队id不能为空",groups={UpdateBase.class,Update.class})
    private Integer id;

    private Date gmtCreate;
    private Date gmtModified;

    @NotBlank(message="团队名称不能为空",groups={Add.class,UpdateBase.class})
    @Length(max=32,message="团队名称字符过长",groups={Add.class,UpdateBase.class})
    private String name;

//    @NotBlank(message="团队logo不能为空",groups={Add.class,UpdateBase.class})
    private String logoImage;

    private Integer creator;

    private Integer memberNumber;

//    @NotBlank(message="团队封面图片不能为空",groups={Update.class})
    private String coverImage;

//    @NotBlank(message="团队简介不能为空",groups={Update.class})
    @Length(max=512,message="团队简介字符过长")
    private String introduction;

    private String qrcodeImage;

    private Integer yesterdayTraffic;

    private Byte settingVisible;

    private Byte settingSpeak;

    private Byte settingActivity;

    private Byte settingNotice;

    private Byte settingVote;

    private Byte status;

    private Integer collectionNumber;
    
    @NotBlank(message="至少需要一个团队标签",groups={Add.class})
    private String labels;
    
    private String college;
    
    private UserAccount user;
    


	public String getCollege() {
		return college;
	}

	public void setCollege(String college) {
		this.college = college;
	}

	/**
	 * @return the user
	 */
	public UserAccount getUser() {
		return user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(UserAccount user) {
		this.user = user;
	}

	/**
	 * @return the labels
	 */
	public String getLabels() {
		return labels;
	}

	/**
	 * @param labels the labels to set
	 */
	public void setLabels(String labels) {
		this.labels = labels;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.id
     *
     * @return the value of club_info.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.id
     *
     * @param id the value for club_info.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.gmt_create
     *
     * @return the value of club_info.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.gmt_create
     *
     * @param gmtCreate the value for club_info.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.gmt_modified
     *
     * @return the value of club_info.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.gmt_modified
     *
     * @param gmtModified the value for club_info.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.name
     *
     * @return the value of club_info.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.name
     *
     * @param name the value for club_info.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.logo_image
     *
     * @return the value of club_info.logo_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getLogoImage() {
        return logoImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.logo_image
     *
     * @param logoImage the value for club_info.logo_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setLogoImage(String logoImage) {
        this.logoImage = logoImage == null ? null : logoImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.creator
     *
     * @return the value of club_info.creator
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.creator
     *
     * @param creator the value for club_info.creator
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.member_number
     *
     * @return the value of club_info.member_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberNumber() {
        return memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.member_number
     *
     * @param memberNumber the value for club_info.member_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberNumber(Integer memberNumber) {
        this.memberNumber = memberNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.cover_image
     *
     * @return the value of club_info.cover_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getCoverImage() {
        return coverImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.cover_image
     *
     * @param coverImage the value for club_info.cover_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCoverImage(String coverImage) {
        this.coverImage = coverImage == null ? null : coverImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.introduction
     *
     * @return the value of club_info.introduction
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.introduction
     *
     * @param introduction the value for club_info.introduction
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.qrcode_image
     *
     * @return the value of club_info.qrcode_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getQrcodeImage() {
        return qrcodeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.qrcode_image
     *
     * @param qrcodeImage the value for club_info.qrcode_image
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setQrcodeImage(String qrcodeImage) {
        this.qrcodeImage = qrcodeImage == null ? null : qrcodeImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.yesterday_traffic
     *
     * @return the value of club_info.yesterday_traffic
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getYesterdayTraffic() {
        return yesterdayTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.yesterday_traffic
     *
     * @param yesterdayTraffic the value for club_info.yesterday_traffic
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setYesterdayTraffic(Integer yesterdayTraffic) {
        this.yesterdayTraffic = yesterdayTraffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.setting_visible
     *
     * @return the value of club_info.setting_visible
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getSettingVisible() {
        return settingVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.setting_visible
     *
     * @param settingVisible the value for club_info.setting_visible
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSettingVisible(Byte settingVisible) {
        this.settingVisible = settingVisible;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.setting_speak
     *
     * @return the value of club_info.setting_speak
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getSettingSpeak() {
        return settingSpeak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.setting_speak
     *
     * @param settingSpeak the value for club_info.setting_speak
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSettingSpeak(Byte settingSpeak) {
        this.settingSpeak = settingSpeak;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.setting_activity
     *
     * @return the value of club_info.setting_activity
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getSettingActivity() {
        return settingActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.setting_activity
     *
     * @param settingActivity the value for club_info.setting_activity
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSettingActivity(Byte settingActivity) {
        this.settingActivity = settingActivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.setting_notice
     *
     * @return the value of club_info.setting_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getSettingNotice() {
        return settingNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.setting_notice
     *
     * @param settingNotice the value for club_info.setting_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSettingNotice(Byte settingNotice) {
        this.settingNotice = settingNotice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.setting_vote
     *
     * @return the value of club_info.setting_vote
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getSettingVote() {
        return settingVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.setting_vote
     *
     * @param settingVote the value for club_info.setting_vote
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSettingVote(Byte settingVote) {
        this.settingVote = settingVote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.status
     *
     * @return the value of club_info.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.status
     *
     * @param status the value for club_info.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_info.collection_number
     *
     * @return the value of club_info.collection_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getCollectionNumber() {
        return collectionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_info.collection_number
     *
     * @param collectionNumber the value for club_info.collection_number
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCollectionNumber(Integer collectionNumber) {
        this.collectionNumber = collectionNumber;
    }
}