package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;
import java.util.List;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;

public class ClubSpeak {
    private Long id;

    private Integer clubId;

    private Integer presentor;

    private Date gmtCreate;

    @NotBlank(message="发表内容不能为空")
    @Length(max=256,message="发表内容字符过长")
    private String content;

    private Byte itsaidFlag;

    private Integer likeAmount;

    private Integer commentAmount;

    private Byte status;
    
    private List<Photo> photos;
    
    

	/**
	 * @return the photos
	 */
	public List<Photo> getPhotos() {
		return photos;
	}

	/**
	 * @param photos the photos to set
	 */
	public void setPhotos(List<Photo> photos) {
		this.photos = photos;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.id
     *
     * @return the value of club_speak.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.id
     *
     * @param id the value for club_speak.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.club_id
     *
     * @return the value of club_speak.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.club_id
     *
     * @param clubId the value for club_speak.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.presentor
     *
     * @return the value of club_speak.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getPresentor() {
        return presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.presentor
     *
     * @param presentor the value for club_speak.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPresentor(Integer presentor) {
        this.presentor = presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.gmt_create
     *
     * @return the value of club_speak.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.gmt_create
     *
     * @param gmtCreate the value for club_speak.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.content
     *
     * @return the value of club_speak.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.content
     *
     * @param content the value for club_speak.content
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.itsaid_flag
     *
     * @return the value of club_speak.itsaid_flag
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getItsaidFlag() {
        return itsaidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.itsaid_flag
     *
     * @param itsaidFlag the value for club_speak.itsaid_flag
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setItsaidFlag(Byte itsaidFlag) {
        this.itsaidFlag = itsaidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.like_amount
     *
     * @return the value of club_speak.like_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getLikeAmount() {
        return likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.like_amount
     *
     * @param likeAmount the value for club_speak.like_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setLikeAmount(Integer likeAmount) {
        this.likeAmount = likeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.comment_amount
     *
     * @return the value of club_speak.comment_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getCommentAmount() {
        return commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.comment_amount
     *
     * @param commentAmount the value for club_speak.comment_amount
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setCommentAmount(Integer commentAmount) {
        this.commentAmount = commentAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak.status
     *
     * @return the value of club_speak.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak.status
     *
     * @param status the value for club_speak.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}