package com.chinamobile.hnu.xiangyu.club.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class ClubLabel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_label.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer clubId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_label.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private String name;
    
    
    /**
   	 * 
   	 */
   	public ClubLabel() {
   		super();
   	}
    

    /**
	 * @param clubId
	 * @param name
	 */
	public ClubLabel(Integer clubId, String name) {
		super();
		this.clubId = clubId;
		this.name = name;
	}





	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_label.id
     *
     * @return the value of club_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_label.id
     *
     * @param id the value for club_label.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_label.club_id
     *
     * @return the value of club_label.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_label.club_id
     *
     * @param clubId the value for club_label.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_label.name
     *
     * @return the value of club_label.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getName() {
        return name;
    }
    
	
	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_label.name
     *
     * @param name the value for club_label.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}