package com.chinamobile.hnu.xiangyu.club.pojo;

public class ClubSpeakLikeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_speak_like.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long speakId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_speak_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak_like.speak_id
     *
     * @return the value of club_speak_like.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getSpeakId() {
        return speakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak_like.speak_id
     *
     * @param speakId the value for club_speak_like.speak_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setSpeakId(Long speakId) {
        this.speakId = speakId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_speak_like.member_id
     *
     * @return the value of club_speak_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_speak_like.member_id
     *
     * @param memberId the value for club_speak_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}