package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;

public class ClubActivityApplicant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_activity_applicant.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_activity_applicant.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;
    
    private Long activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_activity_applicant.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Date gmtCreate;

    
    
    /**
	 * @return the activityId
	 */
	public Long getActivityId() {
		return activityId;
	}

	/**
	 * @param activityId the activityId to set
	 */
	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_activity_applicant.id
     *
     * @return the value of club_activity_applicant.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_activity_applicant.id
     *
     * @param id the value for club_activity_applicant.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_activity_applicant.member_id
     *
     * @return the value of club_activity_applicant.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_activity_applicant.member_id
     *
     * @param memberId the value for club_activity_applicant.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_activity_applicant.gmt_create
     *
     * @return the value of club_activity_applicant.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_activity_applicant.gmt_create
     *
     * @param gmtCreate the value for club_activity_applicant.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}