package com.chinamobile.hnu.xiangyu.club.pojo;

public class ClubTeamBuildingLikeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_team_building_like.tb_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long tbId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column club_team_building_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Integer memberId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building_like.tb_id
     *
     * @return the value of club_team_building_like.tb_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getTbId() {
        return tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building_like.tb_id
     *
     * @param tbId the value for club_team_building_like.tb_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setTbId(Long tbId) {
        this.tbId = tbId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_team_building_like.member_id
     *
     * @return the value of club_team_building_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_team_building_like.member_id
     *
     * @param memberId the value for club_team_building_like.member_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }
}