package com.chinamobile.hnu.xiangyu.club.pojo;

import java.util.Date;
import java.util.List;

import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;

public class ClubVoteInfo {
	
    private Long id;

    private Date gmtCreate;

    private Date gmtModified;

    @NotNull(message="团队id不能为空")
    private Integer clubId;

    private Integer presentor;

    @NotBlank(message="投票名称不能为空")
    @Length(max=32,message="投票名称字符过长")
    private String name;

    @NotBlank(message="投票描述不能为空")
    @Length(max=512,message="投票描述字符过长")
    private String introduction;

    @NotNull(message="投票结束时间不能为空")
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm")
    private Date deadline;

    private Byte status;
    
    @NotBlank(message="投票内容不能为空")
    private String content;
    
    private List<ClubVoteQuestion> questions;
    

    
    /**
	 * @return the questions
	 */
	public List<ClubVoteQuestion> getQuestions() {
		return questions;
	}

	/**
	 * @param questions the questions to set
	 */
	public void setQuestions(List<ClubVoteQuestion> questions) {
		this.questions = questions;
	}

	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}

	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.id
     *
     * @return the value of club_vote_info.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.id
     *
     * @param id the value for club_vote_info.id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.gmt_create
     *
     * @return the value of club_vote_info.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.gmt_create
     *
     * @param gmtCreate the value for club_vote_info.gmt_create
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.gmt_modified
     *
     * @return the value of club_vote_info.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.gmt_modified
     *
     * @param gmtModified the value for club_vote_info.gmt_modified
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.club_id
     *
     * @return the value of club_vote_info.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getClubId() {
        return clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.club_id
     *
     * @param clubId the value for club_vote_info.club_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setClubId(Integer clubId) {
        this.clubId = clubId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.presentor
     *
     * @return the value of club_vote_info.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Integer getPresentor() {
        return presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.presentor
     *
     * @param presentor the value for club_vote_info.presentor
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setPresentor(Integer presentor) {
        this.presentor = presentor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.name
     *
     * @return the value of club_vote_info.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.name
     *
     * @param name the value for club_vote_info.name
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.introduction
     *
     * @return the value of club_vote_info.introduction
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.introduction
     *
     * @param introduction the value for club_vote_info.introduction
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.deadline
     *
     * @return the value of club_vote_info.deadline
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.deadline
     *
     * @param deadline the value for club_vote_info.deadline
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column club_vote_info.status
     *
     * @return the value of club_vote_info.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column club_vote_info.status
     *
     * @param status the value for club_vote_info.status
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}