package com.chinamobile.hnu.xiangyu.club.pojo;

public class ClueVoteRecordKey {
	
	
	private Long id;
	
	private Integer presentor;
	
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue_vote_record.option_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long optionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column clue_vote_record.voter_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    private Long voterId;

    
    
    /**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the presentor
	 */
	public Integer getPresentor() {
		return presentor;
	}

	/**
	 * @param presentor the presentor to set
	 */
	public void setPresentor(Integer presentor) {
		this.presentor = presentor;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column clue_vote_record.option_id
     *
     * @return the value of clue_vote_record.option_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public Long getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column clue_vote_record.option_id
     *
     * @param optionId the value for clue_vote_record.option_id
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    public void setOptionId(Long optionId) {
        this.optionId = optionId;
    }

	/**
	 * @return the voterId
	 */
	public Long getVoterId() {
		return voterId;
	}

	/**
	 * @param voterId the voterId to set
	 */
	public void setVoterId(Long voterId) {
		this.voterId = voterId;
	}

   
}