package com.chinamobile.hnu.xiangyu.ask.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.ask.pojo.AskVisitHistory;

public interface AskVisitHistoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(AskVisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(AskVisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	AskVisitHistory selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(AskVisitHistory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table ask_visit_history
	 * 
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(AskVisitHistory record);

	/**
	 * 查询昨天所有问问访问量
	 * 
	 * @return
	 */
	List<AskVisitHistory> selectAllYesterdayVisit(@Param("today") String today,
			@Param("yesterday") String yesterday);
}