/**
 * Copyright ©2016, 长沙豆子信息技术有限公司, All rights reserved.
 */
package com.chinamobile.hnu.xiangyu.common.service;

import java.util.List;

import com.chinamobile.hnu.xiangyu.common.pojo.PubAdvertisement;
import com.chinamobile.hnu.xiangyu.common.pojo.PubConstPlane;
import com.chinamobile.hnu.xiangyu.util.dto.Page;

/**
 * 常量表的操作接口
 * 
 * @author douzisong
 * @date 2016年12月21日
 */
public interface PubConstPlaneService {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	PubConstPlane selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(PubConstPlane record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table pub_const_plane
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(PubConstPlane record);

	/**
	 * 查询类型常量集合
	 * 
	 * @param type
	 * @return
	 */
	List<PubConstPlane> selectPlanesByType(String type);

	/**
	 * 查询广告图片地址
	 * 
	 * @param category
	 * @return
	 */
	List<PubAdvertisement> selectPubAdvertisementByType(Integer category);

	/**
	 * 广告列表(后台)
	 * 
	 * @param pageCurrent
	 * @param pageSize
	 * @return
	 */
	Page<PubAdvertisement> selectAdvAll(Integer pageCurrent, Integer pageSize);

	int insertSelective(PubAdvertisement record);

	int updateByPrimaryKeySelective(PubAdvertisement record);

	/**
	 * 查询类型常量集合(后台)
	 * 
	 * @param type
	 * @return
	 */
	Page<PubConstPlane> selectPlanesByList(Integer pageCurrent,
			Integer pageSize, String type, String name);

	/**
	 * 批量删除禁用项
	 * 
	 * @param idList
	 */
	int deleteBatchDisableById(List<Integer> idList);

}
