package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;

import com.chinamobile.hnu.xiangyu.user.pojo.UserLabel;

public interface UserLabelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(UserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(UserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    UserLabel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(UserLabel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_label
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(UserLabel record);

	/**
	 * 加入用户标签
	 * @param userLabels
	 */
	void insertList(List<UserLabel> userLabels);
	
	/***
	 * 删除用户标签
	 * @param uid
	 */
	void deleteByUid(Integer uid);

	/**
	 * 查询用户标签
	 * @param uid
	 * @return
	 */
	List<UserLabel> selectUserLabel(Integer uid);
}