package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.user.pojo.UserAccount;
import com.chinamobile.hnu.xiangyu.user.vo.UserVo;

public interface UserAccountMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_account
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_account
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_account
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	UserAccount selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_account
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(UserAccount record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_account
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(UserAccount record);

	/**
	 * 通过手机号查询用户
	 * 
	 * @param phone
	 * @return
	 */
	UserAccount selectByPhone(String phone);

	/**
	 * 通过用户id查询用户密码
	 * 
	 * @param userid
	 * @return
	 */
	String selectPassword(Integer userId);

	/**
	 * 检查用户的enable/disable状态
	 * 
	 * @param uid
	 * @return
	 */
	Integer selectEnable(Integer uid);

	/**
	 * 用户列表
	 * 
	 * @param pageCurrent
	 * @param pageSize
	 */
	List<UserVo> selectUserList();

	/**
	 * 会员列表
	 * 
	 * @return
	 */
	List<UserAccount> seleUserList(Map<String, Object> map);

	/**
	 * 通过昵称查询用户
	 * @param nickname
	 * @return
	 */
	UserAccount selectByNickname(String nickname);

	/**
	 * 专家列表
	 * 
	 * @return
	 */
	List<UserAccount> selectExpertList();

}