package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.user.pojo.UserFriend;
import com.chinamobile.hnu.xiangyu.user.pojo.UserFriendKey;

public interface UserFriendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(UserFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    UserFriend selectByPrimaryKey(UserFriendKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(UserFriend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_friend
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(UserFriend record);

	/**
	 * 查询好友信息
	 * @param uidList
	 * @param uid
	 * @return
	 */
	List<UserFriend> selectFriends(@Param("list")List<Integer> uidList, @Param("userId")int uid);
}