package com.chinamobile.hnu.xiangyu.user.dao;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.user.pojo.UserReport;

public interface UserReportMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(UserReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(UserReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	UserReport selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(UserReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(UserReport record);

	/**
	 * 取消收藏
	 * 
	 * @param favorite
	 */
	void delete(UserReport favorite);

	/**
	 * 查询用户是否举报问问
	 * 
	 * @param askid
	 * @param uid
	 * @return
	 */
	UserReport selectByAskId(@Param("askid") Long askid,
			@Param("uid") Integer uid);

	/**
	 * 根据问问id删除举报记录
	 * 
	 * @param askId
	 */
	int deleteReportAskInfo(Long askId);

}