package com.chinamobile.hnu.xiangyu.user.dao;

import com.chinamobile.hnu.xiangyu.user.pojo.UserCertification;
import com.chinamobile.hnu.xiangyu.web.api.vo.UserCertificationInfoVo;

public interface UserCertificationMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(UserCertification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(UserCertification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	UserCertification selectByPrimaryKey(Integer userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(UserCertification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_certification
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(UserCertification record);

	/**
	 * 查询认证会员信息
	 * 
	 * @return
	 */
	UserCertificationInfoVo selectUserInfoByUserId(Integer userId);
}