package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;

import com.chinamobile.hnu.xiangyu.user.pojo.UserReservedQuestion;

public interface UserReservedQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(UserReservedQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(UserReservedQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    UserReservedQuestion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(UserReservedQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_reserved_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(UserReservedQuestion record);

	/**
	 * 插入用户预设问题
	 * @param list
	 */
	void insertList(List<UserReservedQuestion> list);

	/**
	 * 查询用户预设问题
	 * @param uid
	 * @return
	 */
	List<UserReservedQuestion> selctUserReservedQuestion(Integer uid);

	/**
	 * 删除用户预设问题
	 * @param userId
	 */
	void deleteByUid(Integer userId);
}