package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.user.pojo.UserFavorite;
import com.chinamobile.hnu.xiangyu.user.vo.UserFavoriteVo;

public interface UserFavoriteMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(UserFavorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(UserFavorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	UserFavorite selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(UserFavorite record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table user_favorite
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(UserFavorite record);

	/**
	 * 取消收藏
	 * 
	 * @param favorite
	 */
	void delete(UserFavorite favorite);

	/**
	 * 查询用户是否收藏
	 * 
	 * @param id
	 * @return
	 */
	UserFavorite selectByClubId(@Param("clubId") Integer clubId,
			@Param("uid") Integer uid);

	/**
	 * 查询用户是否收藏问问
	 * 
	 * @param askid
	 * @param uid
	 * @return
	 */
	UserFavorite selectByAskId(@Param("askid") Long askid,
			@Param("uid") Integer uid);

	/**
	 * 收藏分页
	 * 
	 * @param map
	 * @return
	 */
	List<UserFavoriteVo> selectByPage(Map<String, Object> map);

	/**
	 * 查询当前用户收藏的所有
	 * 
	 * @param userId
	 * @return
	 */
	List<UserFavorite> selectByUserId(Integer userId);
}