package com.chinamobile.hnu.xiangyu.user.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.user.pojo.UserHistoricalFootprint;
import com.chinamobile.hnu.xiangyu.user.vo.UserHistoricalFootprintVo;

public interface UserHistoricalFootprintMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(UserHistoricalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(UserHistoricalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    UserHistoricalFootprint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(UserHistoricalFootprint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_historical_footprint
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(UserHistoricalFootprint record);

	/**
	 * 足迹分页
	 * @param map
	 * @return
	 */
	List<UserHistoricalFootprintVo> selectByPage(Map<String, Object> map);
}