package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubActivityApplicant;
import com.chinamobile.hnu.xiangyu.club.vo.LikeVo;

public interface ClubActivityApplicantMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(@Param("activityId")Long activityId, @Param("uid")Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubActivityApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubActivityApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubActivityApplicant selectByPrimaryKey(@Param("activityId")Long activityId, @Param("uid")Integer uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubActivityApplicant record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_activity_applicant
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubActivityApplicant record);

	/**
	 * 查询参加活动的人
	 * @param keySet
	 * @return
	 */
	List<LikeVo> selectByActivityIdList(@Param("set")Set<Long> keySet);

	/***
	 * 查询活动参与人员列表
	 * @param id
	 * @return
	 */
	List<LikeVo> selectList(Long id);

}