package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubVoteOption;

public interface ClubVoteOptionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubVoteOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubVoteOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubVoteOption selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubVoteOption record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_option
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubVoteOption record);

	/**
	 * 批量插入选项
	 * 
	 * @param options
	 */
	void insertList(List<ClubVoteOption> options);

	/**
	 * 查询投票的选项集合
	 * 
	 * @param keySet
	 * @return
	 */
	List<ClubVoteOption> selectByQuestionIdList(@Param("set") Set<Long> keySet);

	/**
	 * 修改票数
	 * 
	 * @param optionIds
	 */
	void updateVoteAmount(List<String> optionIds);

	/***
	 * 根据题目获取投票选项(后台)
	 * 
	 * @param questionId
	 * @return
	 */
	List<ClubVoteOption> selectVoteOptionByQuestionId(Long questionId);
}