package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubSpeakLike;
import com.chinamobile.hnu.xiangyu.club.pojo.ClubSpeakLikeKey;
import com.chinamobile.hnu.xiangyu.club.vo.LikeVo;

public interface ClubSpeakLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(ClubSpeakLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubSpeakLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubSpeakLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubSpeakLike selectByPrimaryKey(ClubSpeakLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubSpeakLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubSpeakLike record);

	/**
	 * 查询团言点赞
	 * @param integer
	 * @return
	 */
    List<LikeVo> selectBySpeakIdList(@Param("set")Set<Long> keySet);
}