package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubInfo;
import com.chinamobile.hnu.xiangyu.club.pojo.ClubVisitHistory;
import com.chinamobile.hnu.xiangyu.club.vo.ClubVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.AclubInfoVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.AclubVo;

public interface ClubInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubInfo record);

	/**
	 * 查询团队分页
	 * 
	 * @param map
	 * @return
	 */
	List<ClubVo> selectByPage(Map<String, Object> map);

	/**
	 * 更新团队收藏数
	 * 
	 * @param bizId
	 * @param op
	 */
	void updateCollection(@Param("clubId") Long bizId, @Param("type") Integer op);

	/**
	 * 更新团队人数
	 * 
	 * @param clubId
	 * @param op
	 */
	void updateMember(@Param("clubId") Integer clubId, @Param("type") Integer op);

	/**
	 * 修改团队访问量
	 * 
	 * @param list
	 */
	void updateYesterdayTrafficByList(List<ClubVisitHistory> list);

	/**
	 * 昨日访问量归零
	 */
	void updateYesterdayTrafficToZero();

	/**
	 * 查询多个团队
	 * 
	 * @param clubSet
	 * @return
	 */
	List<ClubVo> selectByIdList(@Param("set") Set<Long> clubSet);

	/**
	 * 后台 团队列表
	 * 
	 * @param map
	 * @return
	 */
	List<AclubVo> selectByclubList(Map<String, Object> map);

	/**
	 * 查询团队详情
	 * 
	 * @param clubId
	 * @return
	 */
	AclubInfoVo selectClubInfoByclubId(Integer clubId);

	/**
	 * 根据标签查询
	 * @param map
	 * @return
	 */
	List<ClubVo> selectByLabelPage(Map<String, Object> map);

	/**
	 * 公众号查询团队
	 * @param map
	 * @return
	 */
	List<ClubVo> selectByGzhPage(Map<String, Object> map);

	/**
	 * 查询社团信息
	 * @param params
	 * @return
	 */
	List<ClubInfo> selectClubInfoByMap(Map<String, Object> params);

}