package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubNotice;
import com.chinamobile.hnu.xiangyu.club.vo.ClubNoticeVo;

public interface ClubNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubNotice selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_notice
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubNotice record);

	/**
	 * 查询团队最新公告
	 * @param id
	 * @return
	 */
	ClubNotice selectTopByClubId(Integer id);

	/**
	 * 公告查询
	 * @param map
	 * @return
	 */
	List<ClubNoticeVo> selectByPage(Map<String, Object> map);
}