package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubMember;
import com.chinamobile.hnu.xiangyu.club.pojo.ClubMemberKey;
import com.chinamobile.hnu.xiangyu.user.pojo.UserAccount;

public interface ClubMemberMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(ClubMemberKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubMember selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubMember record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_member
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubMember record);

	/**
	 * 查询团队最上级成员
	 * 
	 * @param id
	 * @return
	 */
	List<ClubMember> selectTopByClubId(Integer id);

	/**
	 * 查询团队管理员信息
	 * 
	 * @param clubId
	 * @return
	 */
	List<ClubMember> selectAdminByClubId(Integer clubId);

	/**
	 * 删除群成员
	 * 
	 * @param member
	 */
	void delete(ClubMember member);

	/**
	 * 查询群成员，按照roleid排序
	 * 
	 * @param clubId
	 * @return
	 */
	List<ClubMember> selectClubMemberByClubId(Integer clubId);

	/**
	 * 查询用户是否加入过团队
	 * 
	 * @param id
	 * @param uid
	 * @return
	 */
	ClubMember selectUserJoin(@Param("clubId") Integer id,
			@Param("uid") Integer uid);

	/**
	 * 查询群成员（后台）
	 * 
	 * @param clubId
	 * @return
	 */
	List<ClubMember> selectClubMember(Map<String, Object> map);

	/****
	 * 查询用户加入的群
	 * @param id
	 * @return
	 */
	List<ClubMember> selectClubMemberByUid(Integer id);

}