package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.Photo;

public interface ClubTeamBuildingPhotoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(String photoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	Photo selectByPrimaryKey(String photoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(Photo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building_photo
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(Photo record);

	/**
	 * 批量插入图片
	 * 
	 * @param photos
	 */
	void inserList(List<Photo> photos);

	/**
	 * 删除团建图片
	 * 
	 * @param asList
	 */
	void deleteByIdList(List<String> asList);

	/**
	 * 查询团建照片
	 * 
	 * @param keySet
	 * @return
	 */
	List<Photo> selectByTbIdList(@Param("set") Set<Long> keySet);

	/**
	 * 查询团建照片（后台）
	 * 
	 * @param id
	 * @return
	 */
	List<Photo> selectByTbList(Integer id);
}