package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubVoteQuestion;

public interface ClubVoteQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubVoteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubVoteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubVoteQuestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubVoteQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_vote_question
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubVoteQuestion record);

	/**
	 * 批量插入投票内容
	 * @param questions
	 */
	void insertList(List<ClubVoteQuestion> questions);

	/**
	 * 查询投票的内容
	 * @param voteId
	 * @return
	 */
	List<ClubVoteQuestion> selectByVoteId(Long voteId);
}