package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubSpeak;
import com.chinamobile.hnu.xiangyu.club.vo.ClubSpeakVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.ClubSpeackInfoVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.ClubSpeackVo;

public interface ClubSpeakMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubSpeak record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubSpeak record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubSpeak selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubSpeak record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_speak
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubSpeak record);

	/**
	 * 团言分页
	 * 
	 * @param map
	 * @return
	 */
	List<ClubSpeakVo> selectByPage(Map<String, Object> map);

	/**
	 * 更新团言点赞数
	 * 
	 * @param bizId
	 * @param op
	 *            1.点赞+1；2.点赞-1
	 */
	void updateLike(@Param("speakId") Long speakId, @Param("type") Integer op);

	/**
	 * 更新团言评论数
	 * 
	 * @param clubId
	 * @param op
	 *            1.评论+1；2.评论-1
	 */
	void updateComment(@Param("speakId") Long speakId, @Param("type") Integer op);

	/**
	 * 查询最新团言
	 * 
	 * @param keySet
	 * @return
	 */
	List<ClubSpeakVo> selectTopClubSpeakBySet(@Param("set") Set<Integer> keySet);

	/**
	 * 团言列表(后台)
	 * 
	 * @param map
	 * @return
	 */
	List<ClubSpeackVo> selectClubSpeakList(Map<String, Object> map);

	/**
	 * 团言详情(后台)
	 * 
	 * @param id
	 * @return
	 */
	ClubSpeackInfoVo selectClubSpeakInfo(Long id);

	/***
	 * 查询详情
	 * @param id
	 * @return
	 */
	ClubSpeakVo selectDetaiById(Long id);

}