package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubVoteInfo;
import com.chinamobile.hnu.xiangyu.club.vo.ClubVoteVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.ClubSpeackVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.VoteInfoVo;

public interface ClubVoteInfoMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubVoteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubVoteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubVoteInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubVoteInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_vote_info
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubVoteInfo record);

	/**
	 * 投票分页
	 * 
	 * @param map
	 * @return
	 */
	List<ClubVoteVo> selectByPage(Map<String, Object> map);

	/**
	 * 查询所有正在进行的投票
	 * 
	 * @return
	 */
	List<ClubVoteInfo> selectAllClubVote();

	/**
	 * 修改状态为关闭
	 * 
	 * @param voteIds
	 */
	void updateStatus(List<Long> voteIds);

	/**
	 * @param map
	 * @return
	 */
	List<ClubSpeackVo> selectVoteList(Map<String, Object> map);

	/**
	 * 投票详情(后台)
	 * 
	 * @param voteId
	 * @return
	 */
	List<VoteInfoVo> selectVoteInfoByVoteId(Long voteId);
}