package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubVisitHistory;

public interface ClubVisitHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubVisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubVisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubVisitHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubVisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_visit_history
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubVisitHistory record);

	/**
	 * 查询该用户今日是否访问过该团队
	 * @param uid
	 * @param id
	 * @param formatSimple
	 * @return
	 */
	ClubVisitHistory selectDayVisitToUser(@Param("uid")Integer uid, @Param("clubId")Integer id, @Param("today")String today);

	/**
	 * 查询昨天所有团队访问量
	 * @return
	 */
	List<ClubVisitHistory> selectAllYesterdayVisit(@Param("today")String today,@Param("yesterday")String yesterday);
}