package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubTeamBuildingComment;
import com.chinamobile.hnu.xiangyu.club.vo.CommentVo;

public interface ClubTeamBuildingCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubTeamBuildingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubTeamBuildingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubTeamBuildingComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubTeamBuildingComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubTeamBuildingComment record);

	/**
	 * 查询团建评论分页
	 * @param map
	 * @return
	 */
	List<CommentVo> selectByPage(Map<String, Object> map);
}