package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubTeamBuildingLike;
import com.chinamobile.hnu.xiangyu.club.pojo.ClubTeamBuildingLikeKey;
import com.chinamobile.hnu.xiangyu.club.vo.LikeVo;

public interface ClubTeamBuildingLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(ClubTeamBuildingLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubTeamBuildingLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubTeamBuildingLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubTeamBuildingLike selectByPrimaryKey(ClubTeamBuildingLikeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubTeamBuildingLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_team_building_like
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubTeamBuildingLike record);

	/**
	 * 查询点赞人信息
	 * @param keySet
	 * @return
	 */
	List<LikeVo> selectByTbIdList(@Param("set")Set<Long> keySet);
}