package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;
import java.util.Set;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubActivity;
import com.chinamobile.hnu.xiangyu.club.vo.ClubActivityVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.AclubActivityInfoVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.AclubActivityVo;

public interface ClubActivityMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubActivity selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubActivity record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_activity
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubActivity record);

	/**
	 * 活动分页
	 * 
	 * @param map
	 * @return
	 */
	List<ClubActivityVo> selectByPage(Map<String, Object> map);

	/**
	 * 查询团队最新活动
	 * 
	 * @param keySet
	 * @return
	 */
	List<ClubActivityVo> selectTopClubActivityBySet(
			@Param("set") Set<Integer> keySet);

	/**
	 * 查询详情
	 * 
	 * @param id
	 * @return
	 */
	ClubActivityVo selectDetail(Long id);

	/**
	 * 更新活动点赞数
	 * 
	 * @param bizId
	 * @param op
	 *            1.点赞+1；2.点赞-1
	 */
	void updateLike(@Param("activityId") Long activityId,
			@Param("type") Integer op);

	/**
	 * 更新活动评论数
	 * 
	 * @param clubId
	 * @param op
	 *            1.评论+1；2.评论-1
	 */
	void updateComment(@Param("activityId") Long activityId,
			@Param("type") Integer op);

	/**
	 * 活动分页(后台)
	 * 
	 * @param map
	 * @return
	 */
	List<AclubActivityVo> selectActivityList(Map<String, Object> map);

	/**
	 * @param id
	 * @return
	 */
	AclubActivityInfoVo selectActivityInfo(Long id);
}