package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubTeamBuilding;
import com.chinamobile.hnu.xiangyu.club.vo.TeamBuildVo;
import com.chinamobile.hnu.xiangyu.web.api.vo.TeamBuildingVo;

public interface ClubTeamBuildingMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insert(ClubTeamBuilding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int insertSelective(ClubTeamBuilding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	ClubTeamBuilding selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKeySelective(ClubTeamBuilding record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table club_team_building
	 *
	 * @mbg.generated Thu May 17 23:34:42 CST 2018
	 */
	int updateByPrimaryKey(ClubTeamBuilding record);

	/**
	 * 更新团建点赞数
	 * 
	 * @param bizId
	 * @param op
	 *            1.点赞+1；2.点赞-1
	 */
	void updateLike(@Param("tbId") Long speakId, @Param("type") Integer op);

	/**
	 * 更新团建评论数
	 * 
	 * @param clubId
	 * @param op
	 *            1.评论+1；2.评论-1
	 */
	void updateComment(@Param("tbId") Long speakId, @Param("type") Integer op);

	/**
	 * 团建分页
	 * 
	 * @param map
	 * @return
	 */
	List<TeamBuildVo> selectByPage(Map<String, Object> map);

	/**
	 * 团建分页（后台）
	 * 
	 * @param map
	 * @return
	 */
	List<TeamBuildingVo> selectTbPage(Map<String, Object> map);

	/**
	 * 团建详情(后台)
	 * 
	 * @param id
	 * @return
	 */
	TeamBuildingVo selectById(Integer id);

}