package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;
import java.util.Map;

import com.chinamobile.hnu.xiangyu.club.pojo.ClubSpeakComment;
import com.chinamobile.hnu.xiangyu.club.vo.CommentVo;

public interface ClubSpeakCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClubSpeakComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClubSpeakComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    ClubSpeakComment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClubSpeakComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table club_speak_comment
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClubSpeakComment record);

	/**
	 * 团言下的评论分页
	 * @param map
	 * @return
	 */
	List<CommentVo> selectByPage(Map<String, Object> map);
}