package com.chinamobile.hnu.xiangyu.club.dao;

import java.util.List;

import com.chinamobile.hnu.xiangyu.club.pojo.ClueVoteRecord;
import com.chinamobile.hnu.xiangyu.club.pojo.ClueVoteRecordKey;

public interface ClueVoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int deleteByPrimaryKey(ClueVoteRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insert(ClueVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int insertSelective(ClueVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    List<ClueVoteRecord> selectByPrimaryKey(ClueVoteRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKeySelective(ClueVoteRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table clue_vote_record
     *
     * @mbg.generated Thu May 17 23:34:42 CST 2018
     */
    int updateByPrimaryKey(ClueVoteRecord record);

	/**
	 * 插入投票记录
	 * @param records
	 */
	void insertList(List<ClueVoteRecord> records);
}